author: "jgoodall@ornl.gov"
description: "Stucco document-service"
filesets:
  includes:
  - README.md
  - LICENSE
  excludes:
  - \.git
  - .*\.go
  depth: 8
settings:
  build: go install -v
  outfiles:
    - doc-service
