language: go
go:
  - 1.3
  - tip
install: "echo 'do not run go get'"
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
