language: go
go:
  - 1.3
  - tip
before_install: 
  - ls -l $HOME/gopath/src/github.com/stucco/document-service/Godeps/_workspace/src/*/*/*
  - nohup go run doc-service.go -port=8000 &
install: "echo 'do not run go get - using godep'"
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
