language: go

go:
- 1.6.x
- 1.7.x
- tip

script: go test .

after_success:
- wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
- chmod a+x ./rerun-test.sh
- "./rerun-test.sh"

notifications:
  slack: sava:lB0VBcWKom3VNlr126hyI04E

deploy:
  provider: releases
  api_key:
    secure: D+Gvm/bvN7hVGyubM1ZfeGZOulGvAkJxWhFUG74HyLevqi7Y/DUNEI7G2VeHwzPBR++b7WQqOwjQRK3ThEI0MPs6QYYUA2+nB89ZrLwQMBeYy2rQt2zZwrDo1fM+3mdZtieWUWSg4gbqp51dT9PfTD4ECLzEFVGXT2prVSTXLiY=
  file: doc-service
  on:
    tags: true
