language: go
go:
- 1.4
- tip
before_install:
- go run doc-service.go -port=8267 &
- sleep 10
install: echo 'do not run go get - using godep'
after_success:
- wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
- chmod a+x ./rerun-test.sh
- "./rerun-test.sh"
notifications:
  slack: sava:lB0VBcWKom3VNlr126hyI04E
deploy:
  provider: releases
  api_key:
    secure: D+Gvm/bvN7hVGyubM1ZfeGZOulGvAkJxWhFUG74HyLevqi7Y/DUNEI7G2VeHwzPBR++b7WQqOwjQRK3ThEI0MPs6QYYUA2+nB89ZrLwQMBeYy2rQt2zZwrDo1fM+3mdZtieWUWSg4gbqp51dT9PfTD4ECLzEFVGXT2prVSTXLiY=
  file: doc-service
  on:
    tags: true
