language: go
go:
  - 1.3
  - tip
before_install: 
  - go run doc-service.go -port=8000 &
  - sleep 10
install: "echo 'do not run go get - using godep'"
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
