default:
  server:
    port: 8118
    cluster: true
  logs:
    # log directory
    dir: logs
    # for valid log levels, see [bunyan docs](https://github.com/trentm/node-bunyan#levels)
    level: info
  riak:
    # array of riak servers: server:port
    servers:
      - 10.10.10.100:8098
    # base name for riak client id
    # a unique number will be assigned to each
    client: stucco-document-service-client
    # pool, used for logging
    pool: stucco-document-service-pool
    bucket: stucco