default:
  port: 8000
  cluster: false
  data:
    dir: data
  logs:
    # log directory
    dir: logs
    # for valid log levels, see [bunyan docs](https://github.com/trentm/node-bunyan#levels)
    level: debug
vagrant:
  port: 8118